version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo Build started on `date`
      - echo "No build steps needed for static HTML"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'